### ISSUE TITLE
Create Lindquist Artwork feature

### ISSUE THREAD

**Issue by dhannad** [ITS-UofIowa/education.uiowa.edu#10]
Requested by Kim Dutchuk.
Involves creating CT, taxonomies, views, pages/templates.

**Comment by joewhitsitt** [comment]
What are the details/requirements of this task. We have not discussed this since I joined the project.

**Comment by UIJean** [comment]
I am working on gathering details on this. The primary faculty on this project is on maternity leave. When everyone is back from break, I will contact another member of the faculty who is involved with the project.

**Comment by UIJean** [comment]
Connected with faculty (Clar Baldus). This is Dr. Datchuk's project and we will need to wait until she returns (approx 2 weeks) for more details. She does have an ILRU course this summer connected to this project.

**Comment by joewhitsitt** [comment]
From @UIJean:

> **Fields:**
> - Catalog # (unique)
> - Title of work
> - Artist (taxonomy)
> - Subject matter (taxonomy)
> - Keywords (taxonomy)
> - Image
> - Additional Information (WYSIWYG field, rich text)
> 
> **Taxonomies:**
> - Subject matter
> - Keywords
> - Artist - I have questions about this one, since I would like to attach name, life dates, nationality, and an additional bio field to these artists to include in views. I am not sure how to achieve this.
> 
> Let me know what else you need on this. I'll send views/displays whenever you want them.

**Comment by joewhitsitt** [comment]
@UIJean some initial questions I have:

- Should Catalog number actually be treated as a number (integer, etc.) or do you simply want a text field for this?
- Should subject matter and/or keyword terms be allowed to be created as you are creating the individual art item or only be referenced (post created)?
- Should artist be single or multiple? Is there ever collaboration pieces?

From what I understand for the Artist, we are essentially creating another person content type with different fields. The art work would then just reference that/those individual/s. We can then include as much or as little of the artist(s) on the art page.

Yes, please send along info about where/how you want all this displayed.

**Comment by UIJean** [comment]
Catalog # text field please.

Referenced. Taxonomy set up before item records added.

Artist is single.

I'm not sure I understand your comments about Artist. There will be a list of artists (with a little info on each). We need to access that list to choose the artist when we enter the artwork record. We also need to be able to filter the list by artist (as well as by keyword, and subject matter).

**Comment by UIJean** [comment]
Regarding displays: 
Listing page - 

- Ability to filter (similar to CRUE pubs) by Artist, Keyword, and Subject Matter - with Apply and reset buttons.
3-wide results that include thumbnail of image with Artist(name) Date of work, and title of work. Clickable to full Artwork page with all fields displayed.

**Comment by UIJean** [comment]
Realizing I forgot a field in the artwork content type: please add a field marked as Date. This field will need to be text, rather than a formatted date. 

Thanks and my apologies.

**Comment by joewhitsitt** [comment]
Notes from yesterday's meeting:

- An artist can be used more than once. I think it would be best to create this as an content type that is pulled into the art content type. Jean said her workflow will be to create all artists first before referencing them on the art content type, so an inline entity form is not needed.
- Only one view, list of all artwork (teasers with focal point cropped images). Filters.
- Individual art pages show full image, additional fields. Clicking image will bring it up in a lightbox showing the title text as caption.

**Comment by joewhitsitt** [comment]
Talked to @UIJean briefly about placement location. A basic page can be created in Production (published/unpublished, doesn't matter) that I can then place the view on using the node ID similar to the book of experts topics.

Initially, I will need this node ID and the path alias (education.uiowa.edu/lindquist-art-project).

Pinning down a permanent path for all this would be ideal, but I can take steps to reduce the amount of time it takes to change the URL path and breadcrumbs of for the art and artist content types.

**Comment by UIJean** [comment]
education.uiowa.edu/lindquist-art-collection
node 5791

**Comment by joewhitsitt** [comment]
This is available for review in DEV: https://education.dev.drupal.uiowa.edu/lindquist-art-collection

**Comment by joewhitsitt** [comment]
The following changes have been requested by the group:

https://education.dev.drupal.uiowa.edu/lindquist-art-collection

- Add the ability to insert content above the search. The regular rich-text editor is fine.
- Convert the KEYWORD filter from auto-fill to dropdown list (to match the other two filter options.
- Add a RESET button to the right of the APPLY button.

https://education.dev.drupal.uiowa.edu/lindquist-art-collection/46-jackpot-t-s%C3%B8lv

- Move the MORE ABOUT THE ARTIST section to the left-side (under the image).
- Remove "Additional Information" header from the display, so that the content of that field can display and aligns with field info above it.

https://education.dev.drupal.uiowa.edu/rut-bryk

- Could we add a listing of OTHER WORKS for the artist?

**Comment by joewhitsitt** [comment]
These changes have been pushed to DEV for review.

OTHER WORKS has been moved to issue #41

**Comment by joewhitsitt** [comment]
Request:
- Could you put the image inside the link tag so clicking on the photo has the same effect as clicking on the title?

**Comment by joewhitsitt** [comment]
I have linked the images within the artwork teasers.

This is now available for review in DEV:
https://education.dev.drupal.uiowa.edu/lindquist-art-collection

**Comment by joewhitsitt** [comment]
This is now in production and ready for use. See #41 going forward.
