### ISSUE TITLE
Shorten Existing Hero Large to 600px

### ISSUE THREAD

**Issue by dhannad** [ITS-UofIowa/education.uiowa.edu#13]
Shorter than audience page big hero. Still include the gold navigation box. When not used, continue to use Background Images (duotones).

**Comment by dhannad** [comment]
This option should be extended to Basic Pages so there can be an option to present a consistent banner throughout a center/service. 
The banner picture should be 2000x600px.
The title/h1 and navigation should be presented similar to that on the standard page template.
This is a top priority request.

**Comment by joewhitsitt** [comment]
This request has been revised after discussion. Currently, COE would like to see a mockup of the large image style reduced to a height of 600px.

**Comment by joewhitsitt** [comment]
Accidentally got closed because develop was set as default branch. Switch to master as default branch. Code is currently in DEV for review.

**Comment by joewhitsitt** [comment]
Based on feedback, the tall image at 600px does not meet the needs of the college, and a medium option is not in scope. Changed the configuration back.
