### ISSUE TITLE
Script issue on gulp

### ISSUE THREAD

**Issue by dhannad** [ITS-UofIowa/education.uiowa.edu#22]
When gulp is run the script for the megamenu is removed from the compressed .js file. Workaround has been to manual paste it back in before push.

**Comment by adamdelaney** [comment]
@dhannad I might be able to help you out with this. I have some example code where we grab js using bower or npm and move the assets into the correct folder for js compression/uglify using a gulp task.

**Comment by joewhitsitt** [comment]
@dhannad was this issue resolved or is it still a problem?

**Comment by joewhitsitt** [comment]
the `education.primary_menu` script appears to be included properly in the compress JS file.
