### ISSUE TITLE
Update ranks filter criteria for /directories

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#24]
panel_pane_faculty_staff_view

**Comment by joewhitsitt** [comment]
Existing ranks have been sent to COE. Waiting for updated list.

**Comment by joewhitsitt** [comment]
This isn't so much blocked, but just needs review. If you are okay with the current ranks, we can close this task, otherwise send me the new ranks and I will update this at the same time as everything else.

**Comment by UIJean** [comment]
I do not have an updated list from administration. You can close this for now. I'll just send a new request if/when they want to make a change. Thanks.

**Comment by joewhitsitt** [comment]
closing for now.
