### ISSUE TITLE
Research Publications

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#26]
- New content type
     - Administrative Title (used for searching in content overview) (not displayed)
     - Citation Text area with formatting options (filtered HTML and all that comes with it okay or do you want a limited selection of formatting options (e.g. bold, italic, link, underline, alignment)
     - Affiliation
     - Tags
- Listing view
     - Filter by affiliation
     - Grouped by affiliation
     - Sort by citation

**Comment by joewhitsitt** [comment]
Questions:
- Does there need to be a content block or other views?
- Does there need to be a permalink view page for a filtered affiliation?

**Comment by joewhitsitt** [comment]
In the past I think I ran into issues with grouped then sorted, so I will have to check on the status of that.

**Comment by joewhitsitt** [comment]
Sounded like Jean and Lois were going to regroup on this feature request. Waiting to hear from them.

**Comment by UIJean** [comment]
Here is the updated request. 

- New Content Type
Administrative Title (used for searching in content overview)(not displayed)
Citation Text with formatting options (filtered HTML and all that comes with it)
Link - Citation text to be linked using this field.
Affiliation - single
Tags - multiple (from new taxonomy)

- Listing View (static page or content block?)
Filter by affiliation
Grouped by tags
Sort (alpha) by citation

**Comment by joewhitsitt** [comment]
Regarding the link field, is it linking over the whole citation text? What if the citation text itself has a link, youtube video, etc.? Limiting the formatting on input (limited custom formatting type) would be easier than stripping unwanted markup post-input and preparing the citation to be linked.

Content block only is fine if you are okay with displaying all items based on the filtering criteria. I do think one page should be setup to show all published citations (no filters). Do you want it just on the basic page content type, or available on other content block enabled types?

**Comment by joewhitsitt** [comment]
Also, Tags. Are you sure you want a separate new taxonomy for this, or would you like to use the existing Tags taxonomy which is used on events and news?

**Comment by UIJean** [comment]
Hi - Hoping I answer all of your questions. Let me know if I missed anything. Linking over the whole text citation.  Content block would be very helpful.  Just on basic page content type is fine. Yes, we need a new taxonomy.

**Comment by joewhitsitt** [comment]
@UIJean 
I think this is ready for initial review/feedback in DEV. Let me know about any issues/permissions etc.

Because you want the link field to encompass the whole citation text area field, I went ahead and created a minimal text formatter that doesn't allow links, anchors, media.

If you want an index view with exposed filtering options, where do you want it to live? Does other content need to be on this page besides the view itself?

example: https://education.dev.drupal.uiowa.edu/test-1

**Comment by UIJean** [comment]
We either need some sort of list of terms anchored to location (on the page, top probably) or some other exposed filtering option. If the H3s have URLs I can just add the HTML list, or you can do something programatically. Which option is best?

**Comment by joewhitsitt** [comment]
How about both a filter and anchors? The anchor ids are just using the tag name. Let me know if they need to be more unique than that. See DEV.

**Comment by UIJean** [comment]
Awesome!

**Comment by UIJean** [comment]
Awesome!

**Comment by UIJean** [comment]
How close are we to having this feature ready to push? The center that uses this has GAs on academic year appointments and I am hoping we can get these records moved before the end of the school year.

**Comment by joewhitsitt** [comment]
https://github.com/ITS-UofIowa/education.uiowa.edu/issues/26#issuecomment-289574233 followed up in email.

Changed filter label to "Filter by topic" based on email feedback.

**Comment by UIJean** [comment]
Thank you, Joe. I think this looks good.
