### ISSUE TITLE
Add Avenir font back in where previously removed

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#27]
see commit 1e2114596a2837f9f27b7199bf1ced12bb393eca for previous locations

**Comment by joewhitsitt** [comment]
Accidentally got closed because develop was set as default branch. Switch to master as default branch. Code is currently in DEV for review.

**Comment by joewhitsitt** [comment]
It was noted that H2 is using the bold avenir and that the additional bold font weight is not necessary. I have removed it and it is now reflected in DEV.

**Comment by UIJean** [comment]
If I add records in DEV, will you be able to move them to production? Or should I wait?

**Comment by joewhitsitt** [comment]
@UIJean 

Not sure what records you are talking about in particular due to the task you posted the comment on, but DEV is only a sandbox and no content will be migrated. Use DEV to create a few test cases. Some normal ones, but also a few odd ones that might trip up the feature.

**Comment by UIJean** [comment]
My apologies. Wrong item. Please delete.
