### ISSUE TITLE
News Content Block - More News Link

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#31]
Requested "more news" link be placed in the bottom-right area of the block that links to a audience/affiliation display of news based on the content block's placement.

**Comment by joewhitsitt** [comment]
_Note: the homepage news block is different than the paragraph field content block._

**Comment by joewhitsitt** [comment]
- Two blocks will have to be addressed.
- If linking to just /news for all, this is an easy change, however if linking to an affiliation, there is currently no news/{affiliation_id} view setup. Do you want me to create that dynamic view?

**Comment by UIJean** [comment]
I think the COE homepage block would link to /news for all. 
The content block NEWS would link to an internal URL (basic page), rather than a dynamic view by affiliation.

**Comment by joewhitsitt** [comment]
Homepage block is just hardcoded.

For the "News" content block, I have just made the link dependent on the link field. New blocks will get a default value, old blocks won't bark at you if you don't have a link filled out. The help text suggests the default values, but the link field can be anything. This was the quickest route and didn't require database updates to touch existing blocks. Let me know if this needs to be more strict.

This is available for review in DEV.

**Comment by UIJean** [comment]
Content block looks great.
