### ISSUE TITLE
Change directory view

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#54]
include filtering for affiliation and person type

**Comment by joewhitsitt** [comment]
A few notes about this:

I tried to use Views Selective Filters for the Rank filter, but it didn't work because there is another ranks filter that eliminates affiliate, emeritus, and grad students. The two don't seem to play nicely together. [Found this issue](https://www.drupal.org/node/2774921) that is related but not fixed.

Instead, I am using Views Selective Filters for affiliation, but a regular filter for Rank with "one of the following" (excluding the same ranks above) "limit to selected". The only problem is that if the taxonomy adds a new term to filter on, the view will have to be updated to include it as part of the selected.

Available for review in DEV

**Comment by UIJean** [comment]
Could you add a reset button on this filter? Thanks.

**Comment by UIJean** [comment]
Thanks. Looks good.
