### ISSUE TITLE
Floating quick links

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#55]
See: https://tippie.uiowa.edu/future-undergraduates

Tippie controls these (3 only) with a separate content type that is referenced into another specific content type.

Yesterday I talked about a global solution, but I am starting to rethink that.

**Comment by joewhitsitt** [comment]
I am currently only placing these on basic pages. If this needs to be expanded, let me know. It will add to development time.

**Comment by joewhitsitt** [comment]
This is available for review in DEV.

**Comment by UIJean** [comment]
Others will weigh in, but I feel these (and the new hero photo/video) should be available on more than just basic pages. A program, service, center, degree option, etc. would all potentially have this messaging.

**Comment by UIJean** [comment]
These look ok.

**Comment by joewhitsitt** [comment]
This is now in STAGE set to be deployed.
