### ISSUE TITLE
News by Affiliation Layout breaks if Summary is populated

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#57]
e.g. "news by affiliation" content block on https://education.uiowa.edu/academic-programs/higher-education-and-student-affairs/program-news-hesa

If the article uses the body text, the body text comes with a default `<p></p>` around it and the line breaks appropriately, however the ones that aren't working appear to use the summary field which comes out raw and doesn't have a `<p>` tag to break the line.

**Comment by joewhitsitt** [comment]
This is now available for review in DEV. I decided to restructure the output to use a teaser view mode and standardize the news content blocks.

**Comment by UIJean** [comment]
It looks like the alignment is off for stories that don't have teaser image. All titles used to align, regardless of whether there was an image or not. Hope I'm being clear.

**Comment by UIJean** [comment]
It looks like the thumbnails are quite a bit bigger now. I'm not sure if that can be adjusted. It would be better if the listing took up less space. - Jean

**Comment by joewhitsitt** [comment]
@UIJean they are bigger because the image/text layout is 25%/75%. With the the sidebar is gone, the width of the whole area is larger and the image width was set to fill the width allowed (25%).

If you want I can change it to 20/80% which will bring the image to about 3px wider than that of the image in production.

Keep in mind, this image changes based on display size and shrinks further before switching to mobile full-width.

**Comment by joewhitsitt** [comment]
This is now in STAGE set to be deployed.
