### ISSUE TITLE
"News" Content Block - Adjust Styling/Image Styles

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#60]
- Change the images to be uniform focal point cropped sizes.
- Remove date
- Equal column heights.

**Comment by joewhitsitt** [comment]
This is in DEV for review.

**Comment by UIJean** [comment]
This is complete. Thank you.

**Comment by joewhitsitt** [comment]
This is now in STAGE set to be deployed.
