### ISSUE TITLE
Featured Content Paragraph Bundle

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#64]
- featured_content paragraph bundle sub-type for use in snp_cards as part of education_paragraphs feature
- register new card view mode programmatically
- [register card view mode node template file](https://github.com/ITS-UofIowa/inrc.law.uiowa.edu/blob/develop/modules/features/inrc_common/inrc_common.module#L206) (link wrapping all, so title itself is not linked, html stripped)
- entity reference field that will display title, image, body teaser/summary if provided and wrap the entire 'card' in a link to the node.
- design may come from College of Education (pending)

**Comment by GaryRidgway** [comment]
completed in https://github.com/ITS-UofIowa/education.uiowa.edu/commit/84fd5fe3f5c428d20f9a7a678061a66d05bd0670

**Comment by joewhitsitt** [comment]
This is in DEV for review.
