### ISSUE TITLE
Allow SNP Statistic

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#65]
Enable Statistic paragraph bundle under Cards.
Check styles to see if they work as-is, otherwise make tweaks.

**Comment by GaryRidgway** [comment]
should be ready to go on golive with this commit for styles https://github.com/ITS-UofIowa/education.uiowa.edu/commit/5104463bedfb49a3c36c34a9e3728f91fbe49480

**Comment by joewhitsitt** [comment]
Made a go-live note to add this bundle to Cards.
