### ISSUE TITLE
Custom Block - Filtered People (formally graduate student listings)

### ISSUE THREAD

**Issue by dhannad** [ITS-UofIowa/education.uiowa.edu#8]
Requirements for this are still being defined. 
Purpose is to give programs ability to display their students, especially important for programs that require clinical hours.

**Comment by dhannad** [comment]
listing like /directories with name (First Last, Working Title, and email) linking to staff-like bio page

**Comment by joewhitsitt** [comment]
Request updated to serve for both graduate student listings and filtered people content block.
- Custom block that displays a paged filtered list of people based on ranks (multi value) and affiliation (single value), alpha sort by last name with AJAX pager.
- Needs to gracefully fallback in design for people without photos.
- Current faculty/{term-id} pages will still exist and can be used.

**Comment by joewhitsitt** [comment]
It appears that providing an option for displaying all or paging the results is not easily feasible using the current method. Since the paging was my suggestion, and that all other blocks only have one display, I am removing this requirement unless it is deemed valuable by the college.

**Comment by joewhitsitt** [comment]
> every person record will have a photo (so no fallback design required)

**Comment by joewhitsitt** [comment]
This functionality is now in DEV for testing/review.

- Available on the basic page content type
- Takes a single rank, multiple affiliations (treated as OR), displays all, order by last name, custom title.
- Displayed similarly to faculty/{term-id} pages

**Comment by joewhitsitt** [comment]
Looks like I flipped my notes. The earlier comment says ranks should be multi, affiliation should be single. I will work on making the switch.

**Comment by joewhitsitt** [comment]
It was also requested that working title is displayed instead of rank. if working title is not filled out, show rank.
